import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/nav/Header";
import Footer from "@/components/Footer";
import localFont from "next/font/local";

const sourceSemibold = localFont({
  src: '../fonts/SourceSansPro-Semibold.otf',
  variable: '--sourceSemibold'
})

const sourceLight = localFont({
  src: '../fonts/SourceSansPro-Light.otf',
  variable: '--sourceLight'
})

export const metadata: Metadata = {
  title: "Dependable Accounting Co.",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/favicon.svg", type: "image/svg+xml" },
      { url: "/favicon.png", type: "image/png" }, 
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sourceSemibold.variable}  ${sourceLight.variable} font-sourceSemibold bg-white`}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}