import type { Metadata } from "next";
import { Joan, Noto_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/nav/Header";
import Footer from "@/components/Footer";

const joan = Joan({
  variable: "--font-joan",
  subsets: ["latin"],
  weight: "400",
});

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dependable Accounting Co.",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/favicon.svg", type: "image/svg+xml" },
      { url: "/favicon.png", type: "image/png" },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${joan.variable} ${notoSans.variable} bg-white`}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
